name: Build React Native Project

# This specifies when the workflow should be triggered
on:
  push:
    branches:
      - main   # Triggers the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the repository code to the build environment

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specifies the Node.js version to use

      - name: Install dependencies
        run: npm install  # Installs the project dependencies

      - name: Build the project
        run: npm run build  # Builds the project

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v2  # This step is optional and uploads the build artifacts
        with:
          name: build
          path: android/app/build/outputs/apk/release/*.apk
